language: java
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: releases
  api_key:
    secure: Fzno/o481R5pIYWcE6+70HLFvs9vNm1LjK+ucbF8jMmBpMPITp+ZVrv4spsVBrqCasWjAybTLM9TDtbBmOuuJ895BgbfaYZKB7iSPcSVWWjO24jJ1p1cdFNqc/0B4haIqaTfeYPTsB9XihLX1GQJW6lU1guUi6WcBTnGp5+hHD6zolY/u39tA0RJQ6jOaliccReZvD6zeoPykN6U2aZ2/s/++8JpOHV9YEzyjXMMsyJ+cV2/yl5lR4/5aRHuxNHTUz0FF9t4azniQncL2Vclk9jrsYmV2yXSGP9VmkpdvfmgzAIQZ55ZkCnL0xw0ecwVCsZTYHHa5Z/mh7ds+ZyIdRc+4r5Kz23WG5r0l4+4uGjR3T57IYL9pRMvrHYpBvCyp0nV9ZATBdcm7MelMphZRo1dvJ8QxKfSdQZqYQFVHnDXSgLIVjuxDVmJ/QoATd7qR8EcXoazSRs3JuPNfcp4OEz1FLmVD6gt4NiPwPjqiC3b69+zzasVL7ohoZkFDnf0pWcr/58T/S92zh7wZfnnxzaS+KYHigyeboSlnOUN0O7ur1cCX7sUhSsEka35IwAyh+9xeJExR1qcHdbEuVMTbMNJ3OjGcS35j58T2zN6JLBpMmR4wQsQ2d/gUXhX7vU+TEBzyLmBW9yj2FS9HQfqHNFZobXz/c1skLUwv0ejUGM=
  file: "FireTweaks.jar"
  skip_cleanup: true
  on:
    tags: true
